### ISSUE TITLE
Updating to latest hyper/tokio versions

### ISSUE THREAD

**Issue by ErwanDL** [routerify/routerify-websocket#3]
Hello @rousan, I am planning to use this plugin for a production Hyper-based websocket application. Would you be interested in help updating the plugin to use the latest hyper (0.14) and tokio (1.x) versions, and ensuring the best compatibility with routerify 2.1 ? I could help with a PR if you're interested.

**Comment by rousan** [comment]
Hey @ErwanDL , Thanks for the issue, If you send a PR, that would be a very valuable help. Thanks.

**Comment by ErwanDL** [comment]
Sounds good, I will start working on it this week. I also have a somewhat unrelated question : is there a way to access State from a websocket handler (like we would with a regular handler by doing `req.data::<State>()`) ? And similarly, is there a way to access additional metadata (additional headers, authentication token, query params...) that the client may have passed in the handshake request ?

I haven't found a way to do that yet, but if the `handler` function provided to `upgrade_ws` could accept a second argument of type `Request`, both of these could be solved. Do you think this would be technically doable ? If so, can you point me to what changes would be required, and I could also try to help with that ?

**Comment by ta3pks** [comment]
this project seems to be dead for long time. I started maintaining an up-to-date version of this library
[here](https://docs.rs/routerify-ws)
@ErwanDL

**Comment by ErwanDL** [comment]
@NikosEfthias I think the Routerify maintainers told me in some other issue to use [hyper-tungstenite](https://github.com/de-vri-es/hyper-tungstenite-rs) instead, and I must say it integrates pretty smoothly with hyper and routerify, I've been using it on a project at work for a few months now.

**Comment by rousan** [comment]
@NikosEfthias @ErwanDL , I just released a latest version with latest versions of hyper/tokio/routerfy: [v3.0.0](https://github.com/routerify/routerify-websocket/releases/tag/v3.0.0)
